### ISSUE TITLE
Move combined big and pobit state machine into terraform module

### ISSUE THREAD

**Issue by frankinspace** [podaac/bignbit#10]
Currently the state machine is defined externally to the terraform module: https://github.com/podaac/bignbit/blob/develop/examples/cumulus-tf/step.tf

To simplify installation, the state machine should be defined as part of the terraform module (https://github.com/podaac/bignbit/tree/develop/terraform). Then, when installed into a cumulus environment, the cumulus workflow would invoke the state machine from the terraform module as opposed to defining each step in the workflow.

There's some documentation on how to call a workflow from a workflow on AWS: https://docs.aws.amazon.com/step-functions/latest/dg/sample-start-workflow.html

**Comment by voxparcxls** [comment]
PR: https://github.com/podaac/bignbit/pull/11
