### ISSUE TITLE
Change apply opera treatment choice and lambda to be specific to HLS

### ISSUE THREAD

**Issue by frankinspace** [podaac/bignbit#16]
The apply opera treatment choice and lambda should both be updated to specify that it is specifically for the opera HLS product.

Should also include updating the configuration key names here: https://github.jpl.nasa.gov/podaac/big-configuration/blob/master/config-files/

**Comment by voxparcxls** [comment]
### Changes:
* bignbit-config:
     * PR:  https://github.com/podaac/bignbit-config/pull/2
