### ISSUE TITLE
Gather test data for OPERA_L3_DSWX-S1_V1

### ISSUE THREAD

**Issue by frankinspace** [podaac/bignbit#19]
1. Run ingest in Cumulus UAT for at least 1 OPERA_L3_DSWX-S1_PROVISIONAL_V0 granule
2. Copy the CMA message from that Cumulus UAT run
3. Modify CMA message to use services SIT/UAT s3 bucket locations
4. Upload the granule data into services SIT/UAT
5. Upload the configuration file for OPERA_L3_DSWX-S1_V1 to services SIT/UAT s3 internal bucket
6. Run the bignbit step function in services account

**Comment by torimcd** [comment]
@frankinspace this is failing in UAT with SQS NonExistentQueue errors on the SendToGITC step. I'm having trouble finding the exact name of the queue it's looking for in the logs but wondering if the bignbit-fake-gitc-IN FIFO queues that are in SIT need to be created manually in UAT to mock this step? Or are we actually sending to GITC's UAT venue here?

**Comment by frankinspace** [comment]
@torimcd yes in UAT we would actually send the message to GIBS for testing. It's interesting that we're getting a NonExistentQueue error, maybe they changed their UAT queue name since we're using the one we've used in the past (https://github.com/podaac/bignbit/blob/release/0.1.1/examples/cumulus-tf/tfvars/uat.tfvars#L6)?

But, given that GIBS isn't working on this during this PI I think that's as far as we can take it for now.

**Comment by frankinspace** [comment]
We have some test data gathered for testing bignbit in services account
