### ISSUE TITLE
BIG terraform failing in SWOT venues due to long lambda name

### ISSUE THREAD

**Issue by frankinspace** [podaac/bignbit#6]
We are seeing this error when attempting to deploy BIG in our swot environments

```
error creating Lambda Function (1): InvalidParameterValueException: 1 validation error detected: Value 'svc-big-podaac-swot-sit-cumulus-copy_harmony_results_to_s3-lambda' at 'functionName' failed to satisfy constraint: Member must have length less than or equal to 64
```
Would it be possible to update the BIG terraform module so this is deployable in our swot-sit/swot-uat/swot-ops environments?

https://jira.jpl.nasa.gov/browse/PODAAC-5618

**Comment by viviant100** [comment]
@voxparcxls  to check with @skorper  for naming.

**Comment by voxparcxls** [comment]
Updated to [svc-big-{}-copy_harmony_output_to_s3-lambda](https://github.jpl.nasa.gov/podaac/browse-image-generator/pull/30)
